name: Build and Package

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]  # 根据需要选择 Python 版本

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt  # 确保 requirements.txt 包含了你的项目依赖

    - name: Build executable
      run: |
        if [[ ${{ matrix.os }} == 'ubuntu-latest' || ${{ matrix.os }} == 'macos-latest' ]]; then
          pyinstaller --onefile --name FontConverter --noconsole FontConverter.py
        elif [[ ${{ matrix.os }} == 'windows-latest' ]]; then
          pyinstaller --onefile --name FontConverter --noconsole FontConverter.py
        fi

    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: FontConverter
        path: dist/FontConverter.exe

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        tag_name: FontConverter_${{ github.run_id }}
        release_name: FontConverter_${{ github.run_id }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
    run: | ls dist/
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/FontConverter.exe
        asset_name: FontConverter.exe
        asset_content_type: application/octet-stream
