name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            build_command: pyinstaller --onefile --name FontConverter FontConverter.py
            artifact_name: FontConverter-linux
          - os: macos-latest
            build_command: pyinstaller --onefile --name FontConverter FontConverter.py
            artifact_name: FontConverter-macos
          - os: windows-latest
            build_command: pyinstaller --onefile --name FontConverter FontConverter.py
            artifact_name: FontConverter-windows.exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PyQt5
        pip install fonttools

    - name: Build executable
      run: ${{ matrix.build_command }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: FontConverter-linux
        path: ./dist/
    - uses: actions/download-artifact@v2
      with:
        name: FontConverter-macos
        path: ./dist/
    - uses: actions/download-artifact@v2
      with:
        name: FontConverter-windows.exe
        path: ./dist/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}-${{ github.event.head_commit.timestamp }}
        release_name: Release ${{ github.run_number }} - ${{ github.event.head_commit.timestamp }}
        draft: false
        prerelease: false

    - name: Upload Release Asset Linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/FontConverter-linux
        asset_name: FontConverter-linux
        asset_content_type: application/octet-stream

    - name: Upload Release Asset macOS
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/FontConverter-macos
        asset_name: FontConverter-macos
        asset_content_type: application/octet-stream

    - name: Upload Release Asset Windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/FontConverter-windows.exe
        asset_name: FontConverter-windows.exe
        asset_content_type: application/octet-stream
