name: Build and Release FontConverter

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 你可以根据需要更改 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pyqt5
        pip install fonttools
        pip install brotli

    - name: Build executable
      run: |
        pyinstaller --onefile --name FontConverter --noconsole FontConverter.py

    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: FontConverter-Windows
        path: dist/FontConverter.exe

  build_macos_x86:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 你可以根据需要更改 Python 版本

    - name: Install dependencies and build
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyqt5 fonttools brotli
        arch -x86_64 pyinstaller --onefile --name FontConverter --noconsole FontConverter.py

    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: FontConverter-macOS-x86
        path: dist/FontConverter

  build_macos_arm:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 你可以根据需要更改 Python 版本

    - name: Install dependencies and build
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyqt5 fonttools brotli
        arch -arm64 pyinstaller --onefile --name FontConverter --noconsole FontConverter.py

    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: FontConverter-macOS-arm
        path: dist/FontConverter

  create_release:
    runs-on: ubuntu-latest
    needs: [build_windows, build_macos_x86, build_macos_arm]

    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v2
      with:
        name: FontConverter-Windows
        path: ./dist

    - name: Download macOS x86 artifact
      uses: actions/download-artifact@v2
      with:
        name: FontConverter-macOS-x86
        path: ./dist

    - name: Download macOS ARM artifact
      uses: actions/download-artifact@v2
      with:
        name: FontConverter-macOS-arm
        path: ./dist

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        tag_name: FontConverter_${{ github.run_id }}
        release_name: FontConverter_${{ github.run_id }}
        draft: false
        prerelease: false

    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/FontConverter.exe
        asset_name: FontConverter-Windows.exe
        asset_content_type: application/octet-stream

    - name: Upload macOS x86 Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/FontConverter
        asset_name: FontConverter-macOS-x86
        asset_content_type: application/octet-stream

    - name: Upload macOS ARM Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/FontConverter
        asset_name: FontConverter-macOS-arm
        asset_content_type: application/octet-stream
