name: Build and Release FontConverter

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable
      run: |
        pyinstaller --onefile --name FontConverter FontConverter.py

    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: FontConverter-Windows
        path: dist/FontConverter.exe

  build_macos_x86:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        brew update
        brew install qt

    - name: Install dependencies and build
      run: |
        python -m pip install --upgrade pip
        arch -x86_64 pip install -r requirements.txt
        arch -x86_64 pyinstaller --onefile --windowed --name FontConverter --distpath dist/x86 FontConverter.py
        codesign --force --deep --sign - dist/x86/FontConverter.app
        xattr -dr com.apple.quarantine dist/x86/FontConverter.app

    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: FontConverter-macOS-x86
        path: dist/x86/FontConverter.app

  build_macos_arm:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        brew update
        brew install qt

    - name: Install dependencies and build
      run: |
        python -m pip install --upgrade pip
        arch -arm64 pip install -r requirements.txt
        arch -arm64 pyinstaller --onefile --windowed --name FontConverter --distpath dist/arm FontConverter.py
        codesign --force --deep --sign - dist/arm/FontConverter.app
        xattr -dr com.apple.quarantine dist/arm/FontConverter.app

    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: FontConverter-macOS-arm
        path: dist/arm/FontConverter.app

  create_release:
    runs-on: ubuntu-latest
    needs: [build_windows, build_macos_x86, build_macos_arm]

    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v2
      with:
        name: FontConverter-Windows
        path: ./dist/FontConverter

    - name: Download macOS x86 artifact
      uses: actions/download-artifact@v2
      with:
        name: FontConverter-macOS-x86
        path: ./dist/x86

    - name: Download macOS ARM artifact
      uses: actions/download-artifact@v2
      with:
        name: FontConverter-macOS-arm
        path: ./dist/arm

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        tag_name: FontConverter_${{ github.run_id }}
        release_name: FontConverter_${{ github.run_id }}
        draft: false
        prerelease: false

    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/FontConverter/FontConverter.exe
        asset_name: FontConverter-Windows.exe
        asset_content_type: application/octet-stream

    - name: Upload macOS x86 Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/x86/FontConverter.app
        asset_name: FontConverter-macOS-x86.app
        asset_content_type: application/octet-stream

    - name: Upload macOS ARM Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/arm/FontConverter.app
        asset_name: FontConverter-macOS-arm.app
        asset_content_type: application/octet-stream
