name: Build and Release macx86

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build_macos_x86:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        brew update
        brew install qt

    - name: Install dependencies and build
      run: |
        python -m pip install --upgrade pip
        arch -x86_64 pip install -r requirements.txt
        arch -x86_64 pyinstaller --onefile --windowed --name FontConverter --distpath dist/x86 FontConverter.py
        codesign --force --deep --sign - dist/x86/FontConverter.app
        xattr -dr com.apple.quarantine dist/x86/FontConverter.app

    - name: List dist/ directory
      run: ls -R dist/

    - name: List dist/x86/ directory
      run: ls -R dist/x86/

    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: FontConverter-macOS-x86
        path: dist/x86/

  create_release:
    runs-on: ubuntu-latest
    needs: build_macos_x86

    steps:
    - name: Download macOS x86 artifact
      uses: actions/download-artifact@v2
      with:
        name: FontConverter-macOS-x86
        path: ./dist/x86

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        tag_name: FontConverter_${{ github.run_id }}
        release_name: FontConverter_${{ github.run_id }}
        draft: false
        prerelease: false

    - name: Upload macOS x86 Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/x86
        asset_name: FontConverter-macOS-x86.zip
        asset_content_type: application/zip
