name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Only trigger on version tags
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Choose your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install PyQt5 fonttools

      - name: Build executable (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --onefile FontConverter.py
          mkdir -p build
          mv dist/FontConverter.exe build/

      - name: Build executable (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          pyinstaller --onefile FontConverter.py
          mkdir -p build
          mv dist/FontConverter build/

      - name: Upload artifact (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: FontConverter-Windows
          path: build/FontConverter.exe

      - name: Upload artifact (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: FontConverter-macOS
          path: build/FontConverter

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: FontConverter-Windows
          path: build/windows

      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: FontConverter-macOS
          path: build/macos

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_id }}-${{ github.run_number }}
          release_name: FontConverter Release ${{ github.run_id }}-${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Windows executable
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/windows/FontConverter.exe
          asset_name: FontConverter-Windows.exe
          asset_content_type: application/octet-stream

      - name: Upload macOS executable
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/macos/FontConverter
          asset_name: FontConverter-macOS
          asset_content_type: application/octet-stream
